"""added createdAt and updatedAt to postLikes table

Revision ID: 0198e9b363dc
Revises: 2cd6bb8f7ca4
Create Date: 2022-04-03 01:27:10.886070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0198e9b363dc'
down_revision = '2cd6bb8f7ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postLikes', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('postLikes', sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postLikes', 'updatedAt')
    op.drop_column('postLikes', 'createdAt')
    # ### end Alembic commands ###
